---
knative_serving_version: v0.22.0

knative_serving_crds: "https://github.com/knative/serving/releases/download/{{ knative_serving_version }}/serving-crds.yaml"
knative_serving_core: "https://github.com/knative/serving/releases/download/{{ knative_serving_version }}/serving-core.yaml"
knative_serving_net_istio: "https://github.com/knative/net-istio/releases/download/{{ knative_serving_version }}/net-istio.yaml"

knative_serving_wait_for_deployments: true
